---

fail_fast: false
minimum_pre_commit_version: "2.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "templates/.*"
      - id: mixed-line-ending
      #      - id: trailing-whitespace
      #- id: flake8

  - repo: https://github.com/aws-ia/pre-commit-hooks
    rev: 16be3ef859223383f402c8523bfd3bbb5f750894  # frozen: v1.0
    hooks:
      - id: git-submodule-sanity-check
        always_run: true
  - repo: local
    hooks:
      - id: restricted-filenames
        name: Check commits for unexpected file extensions
        entry: These files are prohibited and should be removed.
        language: fail
        files: '.*\.(taskcat_overrides.yml)'
  - repo: https://github.com/PyCQA/bandit
    rev: 1ed79063e3672a1c6d91ee27cb648e07a7465344  # frozen: 1.7.4
    hooks:
      - id: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        args: ["-c", "pyproject.toml", "-v"]
        additional_dependencies: [ "bandit[toml]" ]
  - repo: https://github.com/psf/black
    rev: 2018e667a6a36ee3fbfa8041cd36512f92f60d49  # frozen: 22.8.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort
        name: isort
